### ISSUE TITLE
Can you add name/label for inputs parameter ?

### ISSUE THREAD

**Issue by mareknowakpgs** [PGSSoft/XCTestParametrizedMacro#9]
Adding @Parametrize(input: []) value to the array creates really long name for the test method. Can you for example add something like a link name/title/label for a single input value? Based on this value you can create the test method's name. What do you think about that?

**Comment by mkowalski87** [comment]
Thanks for the feedback.

To is on our to-do list.
As soon as we have support for an array of expected values we start working on labels to have more meaningful names.

**Comment by mkowalski87** [comment]
done @mareknowakpgs, you can pull changes from main branch
